<a href="https://colab.research.google.com/github/USMS-FPK-IA-GI-2025/controle-01-numpy-and-matplotlib-iris-YoussefDIDI79/blob/main/notebooks/controle_numpy_matplotlib.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Contrôle 01 — Data Science avec NumPy et Matplotlib
**Master 1 — Intelligence Artificielle & Génie Informatique (FPK / USMS)**

Nom & Prénom :  
Filière :  
Année universitaire :

---

**Règles :**
- Bibliothèques autorisées : NumPy, Matplotlib
- Toute autre bibliothèque est interdite
- Chaque question doit être traitée dans une cellule dédiée
- Chaque résultat doit être brièvement interprété


# Partie A — Importation du Dataset, Arrays, Premières Manipulations

### A1. Importation du dataset
Importez NumPy et Matplotlib.  
Chargez le fichier `iris.csv` avec `np.genfromtxt` (`delimiter=','`, `skip_header=1`).  
Stockez les données dans un array nommé `data` et affichez sa `shape`.


In [2]:
# Votre code ici
import numpy as np
import matplotlib.pyplot as plt
data = np.genfromtxt("Iris.csv" , delimiter="," , skip_header=1 , dtype='str')
print(data.shape)


(150, 6)


### A2. Séparation des features et des espèces
Séparez :
- les 4 premières colonnes numériques dans un array `features`
- la dernière colonne (espèces) dans un array `species`
Utilisez le slicing.


In [3]:
# Votre code ici
features = data[:,1:5].astype(float)
species = data[:,-1]
species

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versic

### A3. Indexing
Affichez les 5 premières lignes de `features` en utilisant l’indexing.


In [4]:
# Votre code ici
features[0:5,:]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

### A4. Extraction d’une colonne
Créez un array `sepal_length` contenant uniquement la première colonne de `features`.  
Affichez sa `size` et son `dtype`.


In [5]:
# Votre code ici
sepal_length = features[:,0]
print(sepal_length.size)
print(sepal_length.dtype)

150
float64


### A5. Slicing par espèce
Utilisez le slicing pour extraire les 50 premières lignes correspondant à l’espèce *Setosa*.  
Stockez-les dans `setosa_features`.


In [19]:
# Votre code ici
sts = np.where(species == 'Iris-setosa')[0]
setosa_features = features[sts[:50]]
setosa_features

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

# Partie B — Statistiques Basiques et Opérations Mathématiques

### B6. Moyenne par colonne
Calculez la moyenne de chaque colonne de `features` avec `np.mean(axis=0)`.


In [8]:
# Votre code ici
Moyenne = np.mean(features , axis=0)
print(Moyenne)

[5.84333333 3.054      3.75866667 1.19866667]


### B7. Min et Max
Trouvez la valeur minimale et maximale de la longueur des pétales.


In [16]:
# Votre code ici
m = features[:,2]
Min = np.min(m)
Max = np.max(m)
Min , Max

(np.float64(1.0), np.float64(6.9))

### B9. Normalisation
Normalisez les longueurs des pétales en les divisant par leur maximum.
Stockez le résultat dans `normalized_petals`.


In [18]:
# Votre code ici
normalized_petals = (m / Max)
normalized_petals

array([0.20289855, 0.20289855, 0.1884058 , 0.2173913 , 0.20289855,
       0.24637681, 0.20289855, 0.2173913 , 0.20289855, 0.2173913 ,
       0.2173913 , 0.23188406, 0.20289855, 0.15942029, 0.17391304,
       0.2173913 , 0.1884058 , 0.20289855, 0.24637681, 0.2173913 ,
       0.24637681, 0.2173913 , 0.14492754, 0.24637681, 0.27536232,
       0.23188406, 0.23188406, 0.2173913 , 0.20289855, 0.23188406,
       0.23188406, 0.2173913 , 0.2173913 , 0.20289855, 0.2173913 ,
       0.17391304, 0.1884058 , 0.2173913 , 0.1884058 , 0.2173913 ,
       0.1884058 , 0.1884058 , 0.1884058 , 0.23188406, 0.27536232,
       0.20289855, 0.23188406, 0.20289855, 0.2173913 , 0.20289855,
       0.68115942, 0.65217391, 0.71014493, 0.57971014, 0.66666667,
       0.65217391, 0.68115942, 0.47826087, 0.66666667, 0.56521739,
       0.50724638, 0.60869565, 0.57971014, 0.68115942, 0.52173913,
       0.63768116, 0.65217391, 0.5942029 , 0.65217391, 0.56521739,
       0.69565217, 0.57971014, 0.71014493, 0.68115942, 0.62318

### B10. Somme cumulée
Calculez la somme cumulée des largeurs des pétales pour Versicolor.
Affichez les 10 premières valeurs.


In [24]:
# Votre code ici
vsc = np.where(species == 'Iris-versicolor')[0]
largeurspe_vsc = features[vsc , 3]
la_somme = np.cumsum(largeurspe_vsc)
la_somme10 = la_somme[:10]
la_somme10

array([ 1.4,  2.9,  4.4,  5.7,  7.2,  8.5, 10.1, 11.1, 12.4, 13.8])

### B10. Somme cumulée
Calculez la somme cumulée des largeurs des pétales pour Versicolor.
Affichez les 10 premières valeurs.


In [ ]:
# Votre code ici


# Partie C — Transformations Avancées avec NumPy

### C11. Espèces uniques
Listez les espèces uniques avec `np.unique` et comptez leurs occurrences.


In [ ]:
# Votre code ici


### C12. Reshape par espèce
Transformez `features` en un array de forme `(3, 50, 4)` nommé `features_by_species`.


In [ ]:
# Votre code ici


### C13. Concaténation
Concaténez horizontalement les moyennes par colonne avec un array de zéros.


In [ ]:
# Votre code ici


### C14. Data cleaning (simulation)
Simulez des valeurs NaN et remplacez-les avec `np.nan_to_num`.


In [ ]:
# Votre code ici


### C15. Broadcasting
Ajoutez 1 à toutes les valeurs de la première colonne de `features`.


In [ ]:
# Votre code ici


### C16. np.where
Créez un array binaire indiquant si la longueur des pétales est supérieure à 4.0.


In [ ]:
# Votre code ici


# Partie D — Visualisation avec Matplotlib (Plots Simples)

### D17. Line plot
Line plot des longueurs des sépales pour les 50 premières fleurs.


In [ ]:
# Votre code ici


### D18. Scatter plot
Scatter plot : longueur vs largeur des pétales.


In [ ]:
# Votre code ici


### D19. Bar chart
Bar chart des moyennes des quatre caractéristiques.


In [ ]:
# Votre code ici


### D20. Histogram
Histogramme de la largeur des sépales (10 bins).


In [ ]:
# Votre code ici


### D21. Boxplot par espèce
Boxplot des longueurs des pétales par espèce.


In [ ]:
# Votre code ici


# Partie E — Visualisations Avancées

### E22. Subplots comparatifs
Deux scatter plots côte à côte : Setosa vs Versicolor.


In [ ]:
# Votre code ici


### E23. Grille 2x2
Histogrammes des 4 caractéristiques avec `plt.subplots(2,2)`.


In [ ]:
# Votre code ici


### E24. Bar chart avec error bars
Moyennes par espèce avec écart-type.


In [ ]:
# Votre code ici


### E25. Scatter coloré par espèce
Scatter plot avec couleurs par espèce.


In [ ]:
# Votre code ici


### E26. Line plot superposé
Cumsum des largeurs des pétales par espèce.


In [ ]:
# Votre code ici


# Partie F — Mini-Analyse Finale

### F27. Corrélations
Calculez la matrice de corrélation avec `np.corrcoef`.


In [ ]:
# Votre code ici


### F28. Visualisation des corrélations
Visualisez les corrélations sous forme de bar chart ou scatter.


In [ ]:
# Votre code ici


### F29. Variance par espèce
Identifiez l’espèce avec la plus grande variance globale et visualisez ses distributions.


In [ ]:
# Votre code ici


### F30. Conclusion
Rédigez une conclusion contenant **3 insights** issus de votre analyse.


1) ...
2) ...
3) ...